### PR TITLE
Fix #198 close open mustache crashing analysis

### LINKED ISSUE #198: Unopened mustache followed by mustache opening crashes analyzer
Another bug found by #165
Repro is simple:

```
}}{{
```

though what's between the `}}` and `{{`, and what's afterwards doesn't matter.

Stack trace:

```
RangeError: Value not in range: 30                                     
#0      _StringBase.substring (dart:core-patch/string_patch.dart:369)            
#1      EmbeddedDartParser.findMustaches (package:angular_analyzer_plugin/src/converter.dart:421)
#2      HtmlTreeConverter.convert (package:angular_analyzer_plugin/src/converter.dart:60)
#3      HtmlTreeConverter._convertChildren (package:angular_analyzer_plugin/src/converter.dart:211)
#4      HtmlTreeConverter.convert (package:angular_analyzer_plugin/src/converter.dart:53)
#5      HtmlTreeConverter._convertChildren (package:angular_analyzer_plugin/src/converter.dart:211)
#6      HtmlTreeConverter.convert (package:angular_analyzer_plugin/src/converter.dart:53)
#7      TemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:246)
#8      HtmlTemplateResolver.resolve (package:angular_analyzer_plugin/src/resolver.dart:191)
#9      ResolveHtmlTemplateTask.internalPerform (package:angular_analyzer_plugin/src/tasks.dart:1299)
#10     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:321)       
#11     AnalysisTask.perform (package:analyzer/task/model.dart:220)              
#12     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#13     AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:255)
#14     AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1186)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#16     AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1184)
#17     PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:365)
#18     AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:1007)
#19     Future.Future.<anonymous closure> (dart:async/future.dart:118)           
#20     _rootRun (dart:async/zone.dart:1146)                                     
#21     _CustomZone.run (dart:async/zone.dart:1026)                              
#22     _CustomZone.runGuarded (dart:async/zone.dart:924)                        
#23     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)  
#24     _rootRun (dart:async/zone.dart:1150)                                     
#25     _CustomZone.run (dart:async/zone.dart:1026)                              
#26     _CustomZone.runGuarded (dart:async/zone.dart:924)                        
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)  
#28     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#29     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)               
#30     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)           
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

```

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**

### CODE REVIEW

File: analyzer_plugin/lib/src/converter.dart [hunk 1]
```diff
@@ -398,7 +398,7 @@ class EmbeddedDartParser {
         exprEnd = _startsWithWhitespace(text.substring(exprBegin))
             ? exprBegin
             : text.length;
-      } else if (begin == -1) {
+      } else if (begin == -1 || (end != -1 && end < begin)) {
```
Comment (mk13) [inline analyzer_plugin/lib/src/converter.dart]: Negligible, but `end < begin` should suffice.

Comment (MichaelRFairhurst) [inline analyzer_plugin/lib/src/converter.dart]: Ah yes. We've already checked that end != -1
